import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'

const pingAR = Inter({
  subsets: ['latin'],
  variable: '--font-ping-ar',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={pingAR.variable}>
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  )
}
